# Conclusions and future research {#sec-chapter7}

This research has cemented interpretations and suggestions by previous research, while also introducing innovative results. This is of particular interest for the study of the UP in southwestern Iberia, in a region underrepresented in the archaeological record.

As it stands, we have further evidence that there are clear adaptive and resilient behaviours throughout the UP, possibly motivated by changes in the climate, landscapes and resources. Technology changed, following the cultural shifts of western Europe albeit with regionalisations. Similarly, settlement patterns changed, with the Gravettian (c. 32 and 27 ka cal BP) showing short-term occupations with high frequencies of non-local cherts and retouched tools, and Proto-Solutrean and Solutrean (c 26 and 20 ka cal BP) showing long-term occupations with lower frequencies of non-local cherts and retouched tools.

Despite these changes, many key aspects of technological and social organisation remained intact. Local and non-local raw materials remain the same throughout all of the UP sequence. In general, all non-local cherts show higher maintenance and intensive knapping in comparison to local cherts. And finally, all long-distance cherts, remains of past social networks, show us that even contacts across Iberia were maintained.

This last element of resilience is particularly important for the understanding of UP mobility in southwestern Portugal, but also the understanding of western Europe UP hunter-gatherer groups and their dynamics.
The occurrence of cherts from the Cretaceous formations of central Portugal in archaeological sites, both north (Côa Valley) and south (Algarve) seem to be a common occurrence during the UP and a maintained line of connection. The lines that continuously connect territories between western France, northern and central Spain and central Portugal connect widespread hunter-gatherer groups.

The connection of Vale Boi to southern Spain, further expands these long-distance exchanges and social networks across hinterland and coastal western Europe. In this sense, while the Côa Valley may be interpreted as a region for concentration or movement of hunter-gatherer groups, so does Vale Boi (and southwesternmost Iberia) seem to be a key region for the connection between humans and the extension of social networks.

Zooming out of Vale Boi, we may see in western Europe an interconnected web of hunter-gatherer groups, exchanging not only cultural and technological knowledge, but also resources, emphasizing the intricate role of mobility in the survival of modern Humans and the key potential of raw materials for tracing these ancient pathways.

Despite successfully answering the research questions, the work on raw materials at Vale Boi is far from over.

The question of which specific local/regional sources were exploited during the UP remains unanswered. This is especially relevant for understanding the foraging range of hunter-gatherers, especially during long-term settlements when movements were infrequent. These possibly also coincided with abrupt, climatic events, further impacting mobility patterns. A large portion of chert sources are located within a 20 km radius of Vale Boi, associated with coastal resources and possibly with food resources. Another possible source of chert with similar characteristics (macroscopic, petrographic and geochemical) is located at further distances (>80 km). Identifying the presence of these cherts and their proportions within the identified local types could help us further understand the foraging range of Vale Boi hunter-gatherers, expanding it beyond the immediate coastal niche to the wide Algarve territory.

Similarly, while macroscopic differences allowed the possible identification of non-local cherts (e.g., cherts from the Betic range of southern Spain), pXRF did not allow a further association and distinction between these and local cherts.

These questions could be tackled through the use of alternate analytical methods such as LA-ICP-MS for the in-depth chemical characterisation of cherts and REE analysis (rare earth elements). This method is yet to be tested in the current assemblages and geological samples but has yielded successful results in other geoarchaeological studies.

Finally, it is key to address, perhaps a flagrant caveat or gap about our interpretations—one could say the deer in the room. While this dissertation’s aim was to identify patterns in chert use and further characterise the hunter-gatherer behaviour in western Iberia, building upon a larger block of hunter-gatherer groups scattered through the territory, here we researched only Vale Boi.

It is clear that by approaching a territory as broad as southwesternmost Iberia while using a single site, the results may be truncated by the limited sample size. However, as everything in archaeology, our knowledge is limited to the identified and existing sites, assemblages and their preservation.

The UP in western Algarve (and Algarve in general) is not limited to Vale Boi—it is clear that the territory was occupied by hunter-gatherers, whose presence is signaled in several sites across the region (e.g., Ferrel and Cruz da Pedra; Zambujo, 1998). These sites, however, are poorly preserved and the lithic collections highly altered by post-depositional processes or decontextualized—the several analyses conducted in local museums in western Algarve showed that much, providing truncated results that while seemingly showing similar chert types to those seen at Vale Boi, did not allow their inclusion in this study.

So while it is true that we cannot fully characterise a whole region and the complex human behaviours occurring in that region through 10,000 years through one single site, it is also true that Vale Boi is the only multilayered, well contextualized, dated and studied UP site in western Algarve. It is a cornerstone for the knowledge about hunter-gatherer adaptations through the UP and a key puzzle piece for mobility studies across western Europe.
