project:
  type: book

book:
  title: "thesis2024"
  author: "Joana Belmiro"
  date: "12/25/2024"
  chapters:
    - index.qmd
    - summary.qmd
    - intro.qmd
    - article1.qmd
    - article2.qmd
    - geochemistry.qmd
    - article3.qmd
    - discussion.qmd
    - references.qmd
  appendices:
    - appendix1.qmd

bibliography: references.bib

format:
  html:
    theme: cosmos
  pdf:
    number-sections: true
    toc: true
    toc-title: "Table of contents"
    lof: true
    lot: true
    indent: true
  docx: default

editor: visual
