project:
  type: book

book:
  title: "thesis2024"
  author: "Joana Belmiro"
  date: "12/25/2024"
  chapters:
    - index.qmd
    - intro.qmd
    - summary.qmd
    - geochemistry.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt

editor: visual

