project:
  type: book

book:
  title: "thesis2024"
  author: "Joana Belmiro"
  date: "12/25/2024"
  chapters:
    - index.qmd
    - 00-abstract.qmd
    - 01-intro.qmd
    - 02-creating-frames.qmd
    - 03-within-and-beyond.qmd
    - 04-within-chert.qmd
    - 05-stone-to-tool.qmd
    - 06-discussion.qmd
    - 07-conclusion
    - 08-references.qmd
  appendices:
    - 09-som.qmd

bibliography: references.bib

format:
  html:
    theme: cosmos
  pdf:
    documentclass: scrreprt
    number-sections: true
    toc: true
    toc-title: "Table of contents"
    indent: true
    papersize: a4
    linestretch: 2
  docx: default

editor: visual
